#!/bin/bash

usage() 
{
    echo "Usage: limit <session> <limit> <signer>"
    exit 1
}

[[ $# -ne 3 ]] && usage

SESSION="$1"
LIMIT="$2"
SIGNER="$3"

F_ARGS=$(mktemp)
echo -n ${SESSION} > ${F_ARGS}
echo -n ${LIMIT} >> ${F_ARGS}
rsa_sign ${SIGNER} ${F_ARGS}
b64_encode ${F_ARGS}.dgst

SIGN=$(cat ${F_ARGS}.dgst.b64 | tr -d "\n" | sed 's/"/\\"/g ; s/^/"/ ; s/$/"/')

rm ${F_ARGS} ${F_ARGS}.dgst ${F_ARGS}.dgst.b64
echo -n "{\"Args\": [\"limit\", \"${SESSION}\", \"${LIMIT}\", \"${SIGNER}\", ${SIGN}]}"
