# Copyright Luc Yriarte <luc.yriarte@thingagora.org> 2018 
# License: Apache-2.0

version: '2'

networks:
  bclocalnet:

services:
  ca.bc-org.bclocal:
    container_name: ca
    image: hyperledger/fabric-ca:amd64-1.4.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/ca/ca.bc-org.bclocal-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/ca/${ca__CA_KEYFILE}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/tlsca/tlsca.bc-org.bclocal-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/tlsca/${ca__TLS_KEYFILE}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b ${ca__ADMIN}:${ca__PASSWD} -d'
    volumes:
      - ./crypto-config/peerOrganizations/bc-org.bclocal/ca/:/etc/hyperledger/ca/
      - ./crypto-config/peerOrganizations/bc-org.bclocal/tlsca/:/etc/hyperledger/tlsca/
    networks:
      - bclocalnet

  orderer.bclocal:
    container_name: orderer
    image: hyperledger/fabric-orderer:amd64-1.4.4
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/config/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=BlockchainLocalOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/config
        - ./crypto-config/ordererOrganizations/bclocal/orderers/orderer.bclocal/msp/:/etc/hyperledger/msp
        - ./crypto-config/ordererOrganizations/bclocal/orderers/orderer.bclocal/tls/:/etc/hyperledger/tls
    networks:
      - bclocalnet

  peer0.bc-org.bclocal:
    container_name: peer0
    image: hyperledger/fabric-peer:amd64-1.4.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_bclocalnet
      - CORE_PEER_ID=peer0.bc-org.bclocal
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=BlockchainLocalOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/
      - CORE_PEER_ADDRESS=peer0.bc-org.bclocal:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bc-org.bclocal:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/bc-org.bclocal/peers/peer0.bc-org.bclocal/msp:/etc/hyperledger/msp/
        - ./crypto-config/peerOrganizations/bc-org.bclocal/peers/peer0.bc-org.bclocal/tls:/etc/hyperledger/tls/
    networks:
      - bclocalnet

  cli.bc-org.bclocal:
    container_name: cli-bclocal
    image: hyperledger/fabric-tools:amd64-1.4.4
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli.${cli_ORGA}
      - CORE_PEER_ADDRESS=peer0.${cli_ORGA}:7051
      - CORE_PEER_LOCALMSPID=BlockchainLocalOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/user/msp/
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/user/tls/client.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/user/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/user/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../../chaincode/:/opt/gopath/src/blockchain-org/
        - ./../../sdk/cli/util/:/opt/blockchain-org/util/
        - ./session/:/opt/blockchain-org/session/
        - ./crypto-config/peerOrganizations/${cli_ORGA}/users/${cli_USER}@${cli_ORGA}/:/etc/hyperledger/user/
        - ./crypto-config/ordererOrganizations/bclocal/tlsca/:/etc/hyperledger/orderer/
        - ./config/:/etc/hyperledger/config/
    networks:
        - bclocalnet

